import type { ProfileDetail } from '../api/profileApi'
import type { FunctionMapping, GestureSuggestion, Profile } from '../types'

export type ConfigProfileId = 'office' | 'entertainment' | 'game_2d'

type MappingSeed = Omit<FunctionMapping, 'enabled' | 'gesture_options'> & {
  options: GestureSuggestion[]
}

export const configProfiles: Profile[] = [
  {
    id: 'office',
    name: 'Văn phòng',
    description: 'Điều hướng desktop, tài liệu, tab và kéo thả hằng ngày.',
  },
  {
    id: 'entertainment',
    name: 'Giải trí',
    description: 'Điều khiển phát media, âm lượng, phụ đề và tốc độ.',
  },
  {
    id: 'game_2d',
    name: 'Game 2D',
    description: 'Ánh xạ hành động nhanh cho game platformer bằng phím quen thuộc.',
  },
]

export const actionOptions = [
  'mouse.move',
  'mouse.left_click',
  'mouse.right_click',
  'mouse.scroll',
  'mouse.down',
  'mouse.up',
  'mouse.drag',
  'keyboard.hotkey',
  'keyboard.press',
  'keyboard.release',
  'keyboard.switch_tab',
  'keyboard.copy',
  'keyboard.paste',
  'media.play_pause',
  'media.next',
  'media.previous',
  'media.volume_up',
  'media.volume_down',
  'media.seek_forward',
  'media.seek_backward',
  'media.fullscreen',
  'game.left',
  'game.right',
  'game.move_left',
  'game.move_right',
  'game.jump',
  'game.attack',
  'game.dash',
  'game.block',
  'game.crouch',
  'game.skill_1',
]

const pointerGestures: GestureSuggestion[] = [
  {
    id: 'open_palm_move',
    label: 'Lòng bàn tay mở',
    gesture_event: 'open_palm_move',
    gesture: 'Open Palm Move',
    description: 'Mở bàn tay và di chuyển cổ tay để trỏ/chọn vị trí.',
    fit: 'Tự nhiên cho điều hướng con trỏ vì MediaPipe/Hand Landmarker đọc được hướng và vị trí bàn tay.',
  },
  {
    id: 'index_point_move',
    label: 'Trỏ ngón',
    gesture_event: 'index_point_move',
    gesture: 'Index Point Move',
    description: 'Duỗi ngón trỏ, các ngón còn lại thả lỏng để điều hướng mảnh.',
    fit: 'Phù hợp thao tác chính xác hơn khi cần rê trên vùng nhỏ.',
  },
  {
    id: 'pinch_hover_move',
    label: 'Kẹp nhẹ để rê',
    gesture_event: 'pinch_hover_move',
    gesture: 'Pinch Hover Move',
    description: 'Giữ khoảng cách ngón cái-ngón trỏ gần nhau nhưng chưa đóng click.',
    fit: 'Dễ chuyển tiếp sang click hoặc kéo thả.',
  },
]

const clickGestures: GestureSuggestion[] = [
  {
    id: 'pinch_index',
    label: 'Kẹp ngón trỏ',
    gesture_event: 'pinch_index',
    gesture: 'Pinch Index',
    description: 'Chạm ngón cái với ngón trỏ một nhịp ngắn.',
    fit: 'Pinch là cử chỉ chọn phổ biến, ít mỏi và dễ nhận diện qua landmark đầu ngón.',
  },
  {
    id: 'air_tap',
    label: 'Air Tap',
    gesture_event: 'air_tap',
    gesture: 'Air Tap',
    description: 'Hạ nhanh ngón trỏ như bấm một nút trong không trung.',
    fit: 'Tốt cho click đơn khi người dùng quen với kiểu tap.',
  },
  {
    id: 'index_finger_pose',
    label: 'Pose một ngón',
    gesture_event: 'index_finger_pose',
    gesture: 'One Finger Pose',
    description: 'Giữ một ngón trỏ trong 250ms để xác nhận.',
    fit: 'Dễ học, nhưng chỉ nên dùng cho shortcut có phản hồi rõ.',
  },
]

const secondaryClickGestures: GestureSuggestion[] = [
  {
    id: 'pinch_middle',
    label: 'Kẹp ngón giữa',
    gesture_event: 'pinch_middle',
    gesture: 'Pinch Middle',
    description: 'Chạm ngón cái với ngón giữa để phân biệt với click trái.',
    fit: 'Tách rõ với pinch ngón trỏ, hợp cho right-click.',
  },
  {
    id: 'two_finger_tap',
    label: 'Tap hai ngón',
    gesture_event: 'two_finger_tap',
    gesture: 'Two Finger Tap',
    description: 'Duỗi trỏ + giữa rồi tap nhẹ một nhịp.',
    fit: 'Gần với right-click bằng touchpad Windows.',
  },
  {
    id: 'press_hold',
    label: 'Nhấn giữ',
    gesture_event: 'press_hold',
    gesture: 'Press Hold',
    description: 'Giữ bàn tay ổn định trên mục tiêu trong một khoảng ngắn.',
    fit: 'Gần với press-and-hold để mở menu ngữ cảnh trên màn hình cảm ứng.',
  },
]

const dragGestures: GestureSuggestion[] = [
  {
    id: 'pinch_drag',
    label: 'Pinch kéo-thả',
    gesture_event: 'pinch_drag',
    gesture: 'Pinch Hold + Move + Release',
    description: 'Kẹp để giữ, di chuyển tay, mở tay để thả.',
    fit: 'Tự nhiên vì mô phỏng grab-release và giữ đúng state machine kéo-thả.',
  },
  {
    id: 'closed_fist_hold',
    label: 'Nắm tay giữ',
    gesture_event: 'closed_fist_hold',
    gesture: 'Closed Fist Hold',
    description: 'Nắm tay để giữ đối tượng, mở tay để thả.',
    fit: 'Dễ hiểu như thao tác cầm vật thể.',
  },
  {
    id: 'grab_release',
    label: 'Grab Release',
    gesture_event: 'grab_release',
    gesture: 'Grab Release',
    description: 'Co các ngón để grab, duỗi ra để release.',
    fit: 'Phù hợp hướng dẫn hand tracking ưu tiên thao tác grab tự nhiên.',
  },
]

const valueGestures: GestureSuggestion[] = [
  {
    id: 'two_finger_swipe',
    label: 'Vuốt hai ngón',
    gesture_event: 'two_finger_swipe',
    gesture: 'Two Finger Swipe',
    description: 'Vuốt hai ngón theo hướng cần cuộn/tua/chỉnh giá trị.',
    fit: 'Gần với cuộn touchpad Windows bằng hai ngón.',
  },
  {
    id: 'pinch_move_value',
    label: 'Pinch rồi di chuyển',
    gesture_event: 'pinch_move_value',
    gesture: 'Pinch + Move',
    description: 'Kẹp ngón rồi kéo lên/xuống hoặc trái/phải để tăng giảm.',
    fit: 'Hợp cho slider như âm lượng, seek, zoom.',
  },
  {
    id: 'open_palm_swipe',
    label: 'Vuốt lòng bàn tay',
    gesture_event: 'open_palm_swipe',
    gesture: 'Open Palm Swipe',
    description: 'Mở bàn tay và vuốt dứt khoát theo trục thao tác.',
    fit: 'Nhanh, rõ hướng, tốt cho hành động lặp.',
  },
]

const tabGestures: GestureSuggestion[] = [
  {
    id: 'swipe_right',
    label: 'Vuốt phải',
    gesture_event: 'swipe_right',
    gesture: 'Swipe Right',
    description: 'Vuốt ngang sang phải để tới mục tiếp theo.',
    fit: 'Tương ứng next tab/next item theo hướng thị giác.',
  },
  {
    id: 'swipe_left',
    label: 'Vuốt trái',
    gesture_event: 'swipe_left',
    gesture: 'Swipe Left',
    description: 'Vuốt ngang sang trái để quay lại mục trước.',
    fit: 'Tương ứng previous tab/previous item.',
  },
  {
    id: 'three_finger_swipe',
    label: 'Vuốt ba ngón',
    gesture_event: 'three_finger_swipe',
    gesture: 'Three Finger Swipe',
    description: 'Duỗi ba ngón rồi vuốt ngang để chuyển ngữ cảnh.',
    fit: 'Gợi nhớ gesture Windows cho chuyển cửa sổ/task view.',
  },
]

const poseGestures: GestureSuggestion[] = [
  {
    id: 'two_finger_pose',
    label: 'Pose hai ngón',
    gesture_event: 'two_finger_pose',
    gesture: 'Two Finger Pose',
    description: 'Giữ hai ngón trong 300ms để gọi shortcut.',
    fit: 'Tốt cho tác vụ ít dùng, tránh nhầm với điều hướng liên tục.',
  },
  {
    id: 'three_finger_pose',
    label: 'Pose ba ngón',
    gesture_event: 'three_finger_pose',
    gesture: 'Three Finger Pose',
    description: 'Giữ ba ngón để gọi một chế độ hoặc lệnh hệ thống.',
    fit: 'Phù hợp action lớn như task view, inventory, map.',
  },
  {
    id: 'finger_count_shortcut',
    label: 'Shortcut số ngón',
    gesture_event: 'finger_count_shortcut',
    gesture: 'Finger Pose Shortcut',
    description: 'Dùng số ngón làm mã shortcut nhanh.',
    fit: 'Dễ nhớ nếu UI hiển thị hướng dẫn rõ.',
  },
]

const gameGestures: GestureSuggestion[] = [
  {
    id: 'tilt',
    label: 'Nghiêng tay',
    gesture_event: 'tilt',
    gesture: 'Tilt',
    description: 'Nghiêng cổ tay sang hướng di chuyển.',
    fit: 'Tự nhiên cho trái/phải/lên/xuống và không cần pose phức tạp.',
  },
  {
    id: 'swipe_up_down',
    label: 'Vuốt lên/xuống',
    gesture_event: 'swipe_up_down',
    gesture: 'Swipe Up/Down',
    description: 'Vuốt dọc để nhảy, cúi hoặc đổi trục.',
    fit: 'Nhanh, rõ hướng, hợp game 2D.',
  },
  {
    id: 'rapid_punch',
    label: 'Đấm nhanh',
    gesture_event: 'rapid_punch',
    gesture: 'Rapid Punch',
    description: 'Đẩy nắm tay ngắn về phía camera để kích hoạt action.',
    fit: 'Hợp với attack/dash vì phản hồi nhanh và cảm giác vật lý rõ.',
  },
]

const confirmGestures: GestureSuggestion[] = [
  {
    id: 'open_close_palm',
    label: 'Mở-đóng bàn tay',
    gesture_event: 'open_close_palm',
    gesture: 'Open Close Palm',
    description: 'Đóng rồi mở bàn tay một nhịp để toggle.',
    fit: 'Hợp cho play/pause, mute hoặc pause game.',
  },
  {
    id: 'pinch_tap',
    label: 'Pinch Tap',
    gesture_event: 'pinch_tap',
    gesture: 'Pinch Tap',
    description: 'Kẹp nhanh ngón cái-ngón trỏ để xác nhận.',
    fit: 'Chọn nhanh, ít chiếm không gian.',
  },
  {
    id: 'thumbs_up',
    label: 'Thumbs Up',
    gesture_event: 'thumbs_up',
    gesture: 'Thumbs Up',
    description: 'Giơ ngón cái để xác nhận hoặc bật/tắt.',
    fit: 'Dễ hiểu nhưng nên dùng có hướng dẫn vì là learned pose.',
  },
]

const officeFunctions = [
  mapping({
    id: 'move',
    label: 'Di chuyển chuột',
    description: 'Điều hướng con trỏ trên desktop.',
    category: 'Pointer',
    gesture_event: 'open_palm_move',
    gesture: 'Open Palm Move',
    action: 'mouse.move',
    payload: {},
    options: pointerGestures,
  }),
  mapping({
    id: 'left_click',
    label: 'Click trái',
    description: 'Chọn file, nút hoặc ô nhập liệu.',
    category: 'Pointer',
    gesture_event: 'pinch_index',
    gesture: 'Pinch Index',
    action: 'mouse.left_click',
    payload: {},
    options: clickGestures,
  }),
  mapping({
    id: 'right_click',
    label: 'Click phải',
    description: 'Mở menu ngữ cảnh.',
    category: 'Pointer',
    gesture_event: 'pinch_middle',
    gesture: 'Pinch Middle',
    action: 'mouse.right_click',
    payload: {},
    options: secondaryClickGestures,
  }),
  mapping({
    id: 'double_click',
    label: 'Double click',
    description: 'Mở file/thư mục bằng hai nhịp click.',
    category: 'Pointer',
    gesture_event: 'pinch_double',
    gesture: 'Double Pinch',
    action: 'mouse.left_click',
    payload: { clicks: 2 },
    options: clickGestures,
  }),
  mapping({
    id: 'drag_drop',
    label: 'Kéo thả file/thư mục',
    description: 'Giữ, di chuyển và thả đối tượng.',
    category: 'Pointer',
    gesture_event: 'pinch_drag',
    gesture: 'Pinch Hold + Move + Release',
    action: 'mouse.drag',
    payload: { state_machine: ['pinch_start', 'pinch_hold', 'drag_move', 'drag_release'] },
    options: dragGestures,
  }),
  mapping({
    id: 'scroll_up',
    label: 'Cuộn lên',
    description: 'Cuộn tài liệu hoặc trang web lên trên.',
    category: 'Navigation',
    gesture_event: 'two_finger_swipe_up',
    gesture: 'Two Finger Swipe Up',
    action: 'mouse.scroll',
    payload: { amount: 5 },
    options: valueGestures,
  }),
  mapping({
    id: 'scroll_down',
    label: 'Cuộn xuống',
    description: 'Cuộn tài liệu hoặc trang web xuống dưới.',
    category: 'Navigation',
    gesture_event: 'two_finger_swipe_down',
    gesture: 'Two Finger Swipe Down',
    action: 'mouse.scroll',
    payload: { amount: -5 },
    options: valueGestures,
  }),
  mapping({
    id: 'zoom_in',
    label: 'Phóng to',
    description: 'Zoom tài liệu/trình duyệt.',
    category: 'Navigation',
    gesture_event: 'pinch_spread',
    gesture: 'Pinch Spread',
    action: 'keyboard.hotkey',
    payload: { shortcut: 'ctrl+=' },
    options: valueGestures,
  }),
  mapping({
    id: 'zoom_out',
    label: 'Thu nhỏ',
    description: 'Giảm mức zoom tài liệu/trình duyệt.',
    category: 'Navigation',
    gesture_event: 'pinch_contract',
    gesture: 'Pinch Contract',
    action: 'keyboard.hotkey',
    payload: { shortcut: 'ctrl+-' },
    options: valueGestures,
  }),
  mapping({
    id: 'next_tab',
    label: 'Chuyển tab phải',
    description: 'Đi tới tab kế tiếp.',
    category: 'Tabs',
    gesture_event: 'three_finger_swipe_right',
    gesture: 'Three Finger Swipe Right',
    action: 'keyboard.switch_tab',
    payload: { shortcut: 'ctrl+tab' },
    options: tabGestures,
  }),
  mapping({
    id: 'previous_tab',
    label: 'Chuyển tab trái',
    description: 'Quay về tab trước.',
    category: 'Tabs',
    gesture_event: 'three_finger_swipe_left',
    gesture: 'Three Finger Swipe Left',
    action: 'keyboard.hotkey',
    payload: { shortcut: 'ctrl+shift+tab' },
    options: tabGestures,
  }),
  mapping({
    id: 'copy',
    label: 'Copy',
    description: 'Sao chép vùng đang chọn.',
    category: 'Clipboard',
    gesture_event: 'pinch_hold_left',
    gesture: 'Pinch Hold Left',
    action: 'keyboard.copy',
    payload: { shortcut: 'ctrl+c' },
    options: poseGestures,
  }),
  mapping({
    id: 'paste',
    label: 'Paste',
    description: 'Dán nội dung từ clipboard.',
    category: 'Clipboard',
    gesture_event: 'pinch_hold_right',
    gesture: 'Pinch Hold Right',
    action: 'keyboard.paste',
    payload: { shortcut: 'ctrl+v' },
    options: poseGestures,
  }),
  mapping({
    id: 'undo',
    label: 'Undo',
    description: 'Hoàn tác thao tác gần nhất.',
    category: 'Clipboard',
    gesture_event: 'open_palm_twist',
    gesture: 'Open Palm Twist',
    action: 'keyboard.hotkey',
    payload: { shortcut: 'ctrl+z' },
    options: poseGestures,
  }),
  mapping({
    id: 'screenshot',
    label: 'Chụp vùng màn hình',
    description: 'Mở công cụ chọn vùng chụp màn hình.',
    category: 'System',
    gesture_event: 'screen_pinch_capture',
    gesture: 'Screen Pinch Capture',
    action: 'keyboard.hotkey',
    payload: { shortcut: 'win+shift+s' },
    options: poseGestures,
  }),
  mapping({
    id: 'task_view',
    label: 'Task View',
    description: 'Xem nhanh các cửa sổ đang mở.',
    category: 'System',
    gesture_event: 'three_finger_up',
    gesture: 'Three Finger Swipe Up',
    action: 'keyboard.hotkey',
    payload: { shortcut: 'win+tab' },
    options: poseGestures,
  }),
]

const entertainmentFunctions = [
  mapping({
    id: 'play_pause',
    label: 'Play/Pause',
    description: 'Bật hoặc tạm dừng nội dung đang phát.',
    category: 'Playback',
    gesture_event: 'open_close_palm',
    gesture: 'Open Close Palm',
    action: 'media.play_pause',
    payload: { shortcut: 'space' },
    options: confirmGestures,
  }),
  mapping({
    id: 'next_video',
    label: 'Next video',
    description: 'Chuyển sang video/bài tiếp theo.',
    category: 'Playback',
    gesture_event: 'swipe_right',
    gesture: 'Swipe Right',
    action: 'media.next',
    payload: { shortcut: 'media_next' },
    options: tabGestures,
  }),
  mapping({
    id: 'previous_video',
    label: 'Previous video',
    description: 'Quay lại video/bài trước.',
    category: 'Playback',
    gesture_event: 'swipe_left',
    gesture: 'Swipe Left',
    action: 'media.previous',
    payload: { shortcut: 'media_previous' },
    options: tabGestures,
  }),
  mapping({
    id: 'seek_forward',
    label: 'Tua tới 10s',
    description: 'Tua nhanh nội dung về phía trước.',
    category: 'Timeline',
    gesture_event: 'two_finger_swipe_right',
    gesture: 'Two Finger Swipe Right',
    action: 'media.seek_forward',
    payload: { shortcut: 'l', seconds: 10 },
    options: valueGestures,
  }),
  mapping({
    id: 'seek_backward',
    label: 'Tua lùi 10s',
    description: 'Tua lùi nội dung đang phát.',
    category: 'Timeline',
    gesture_event: 'two_finger_swipe_left',
    gesture: 'Two Finger Swipe Left',
    action: 'media.seek_backward',
    payload: { shortcut: 'j', seconds: 10 },
    options: valueGestures,
  }),
  mapping({
    id: 'volume_up',
    label: 'Tăng âm lượng',
    description: 'Tăng âm lượng theo nấc.',
    category: 'Audio',
    gesture_event: 'pinch_move_up_volume',
    gesture: 'Pinch Move Up',
    action: 'media.volume_up',
    payload: { shortcut: 'volume_up' },
    options: valueGestures,
  }),
  mapping({
    id: 'volume_down',
    label: 'Giảm âm lượng',
    description: 'Giảm âm lượng theo nấc.',
    category: 'Audio',
    gesture_event: 'pinch_move_down_volume',
    gesture: 'Pinch Move Down',
    action: 'media.volume_down',
    payload: { shortcut: 'volume_down' },
    options: valueGestures,
  }),
  mapping({
    id: 'mute',
    label: 'Mute/Unmute',
    description: 'Bật hoặc tắt tiếng nhanh.',
    category: 'Audio',
    gesture_event: 'thumbs_up_mute',
    gesture: 'Thumbs Up Toggle',
    action: 'keyboard.hotkey',
    payload: { shortcut: 'm' },
    options: confirmGestures,
  }),
  mapping({
    id: 'fullscreen',
    label: 'Fullscreen',
    description: 'Bật hoặc thoát chế độ toàn màn hình.',
    category: 'View',
    gesture_event: 'open_palm_hold_fullscreen',
    gesture: 'Open Palm Hold',
    action: 'media.fullscreen',
    payload: { shortcut: 'f' },
    options: confirmGestures,
  }),
  mapping({
    id: 'mini_player',
    label: 'Mini player',
    description: 'Mở trình phát thu nhỏ khi xem video.',
    category: 'View',
    gesture_event: 'two_finger_pose_mini',
    gesture: 'Two Finger Pose',
    action: 'keyboard.hotkey',
    payload: { shortcut: 'i' },
    options: poseGestures,
  }),
  mapping({
    id: 'captions',
    label: 'Phụ đề',
    description: 'Bật hoặc tắt captions/subtitles.',
    category: 'View',
    gesture_event: 'three_finger_pose_captions',
    gesture: 'Three Finger Pose',
    action: 'keyboard.hotkey',
    payload: { shortcut: 'c' },
    options: poseGestures,
  }),
  mapping({
    id: 'speed_up',
    label: 'Tăng tốc độ phát',
    description: 'Tăng playback rate.',
    category: 'Timeline',
    gesture_event: 'pinch_move_right_speed',
    gesture: 'Pinch Move Right',
    action: 'keyboard.hotkey',
    payload: { shortcut: 'shift+.' },
    options: valueGestures,
  }),
  mapping({
    id: 'speed_down',
    label: 'Giảm tốc độ phát',
    description: 'Giảm playback rate.',
    category: 'Timeline',
    gesture_event: 'pinch_move_left_speed',
    gesture: 'Pinch Move Left',
    action: 'keyboard.hotkey',
    payload: { shortcut: 'shift+,' },
    options: valueGestures,
  }),
  mapping({
    id: 'next_frame',
    label: 'Frame kế tiếp',
    description: 'Khi video pause, tiến một frame.',
    category: 'Timeline',
    gesture_event: 'finger_pose_next_frame',
    gesture: 'Finger Pose Next',
    action: 'keyboard.hotkey',
    payload: { shortcut: '.' },
    options: poseGestures,
  }),
  mapping({
    id: 'previous_frame',
    label: 'Frame trước',
    description: 'Khi video pause, lùi một frame.',
    category: 'Timeline',
    gesture_event: 'finger_pose_previous_frame',
    gesture: 'Finger Pose Previous',
    action: 'keyboard.hotkey',
    payload: { shortcut: ',' },
    options: poseGestures,
  }),
]

const game2dFunctions = [
  mapping({
    id: 'move_left',
    label: 'Di chuyển trái',
    description: 'Giữ/phát phím A hoặc Left.',
    category: 'Movement',
    gesture_event: 'tilt_left',
    gesture: 'Tilt Left',
    action: 'game.move_left',
    payload: { key: 'a' },
    options: gameGestures,
  }),
  mapping({
    id: 'move_right',
    label: 'Di chuyển phải',
    description: 'Giữ/phát phím D hoặc Right.',
    category: 'Movement',
    gesture_event: 'tilt_right',
    gesture: 'Tilt Right',
    action: 'game.move_right',
    payload: { key: 'd' },
    options: gameGestures,
  }),
  mapping({
    id: 'move_up',
    label: 'Di chuyển lên',
    description: 'Dùng phím W cho menu hoặc game top-down.',
    category: 'Movement',
    gesture_event: 'tilt_up',
    gesture: 'Tilt Up',
    action: 'keyboard.press',
    payload: { key: 'w' },
    options: gameGestures,
  }),
  mapping({
    id: 'move_down',
    label: 'Di chuyển xuống',
    description: 'Dùng phím S cho menu hoặc game top-down.',
    category: 'Movement',
    gesture_event: 'tilt_down',
    gesture: 'Tilt Down',
    action: 'keyboard.press',
    payload: { key: 's' },
    options: gameGestures,
  }),
  mapping({
    id: 'jump',
    label: 'Nhảy',
    description: 'Kích hoạt jump bằng Space.',
    category: 'Movement',
    gesture_event: 'swipe_up',
    gesture: 'Swipe Up',
    action: 'game.jump',
    payload: { key: 'space' },
    options: gameGestures,
  }),
  mapping({
    id: 'crouch',
    label: 'Cúi',
    description: 'Cúi hoặc drop-down platform.',
    category: 'Movement',
    gesture_event: 'swipe_down',
    gesture: 'Swipe Down',
    action: 'game.crouch',
    payload: { key: 's' },
    options: gameGestures,
  }),
  mapping({
    id: 'attack',
    label: 'Tấn công',
    description: 'Đòn đánh thường.',
    category: 'Combat',
    gesture_event: 'rapid_punch',
    gesture: 'Rapid Punch',
    action: 'game.attack',
    payload: { key: 'j' },
    tone: 'red',
    options: gameGestures,
  }),
  mapping({
    id: 'heavy_attack',
    label: 'Tấn công mạnh',
    description: 'Đòn đánh nặng hoặc charged attack.',
    category: 'Combat',
    gesture_event: 'closed_fist_punch',
    gesture: 'Closed Fist Punch',
    action: 'keyboard.press',
    payload: { key: 'l' },
    tone: 'red',
    options: gameGestures,
  }),
  mapping({
    id: 'block',
    label: 'Đỡ đòn',
    description: 'Block/parry bằng phím K.',
    category: 'Combat',
    gesture_event: 'closed_fist_hold',
    gesture: 'Closed Fist Hold',
    action: 'game.block',
    payload: { key: 'k' },
    options: dragGestures,
  }),
  mapping({
    id: 'dash',
    label: 'Dash',
    description: 'Lướt nhanh bằng Shift.',
    category: 'Movement',
    gesture_event: 'swipe_double',
    gesture: 'Double Swipe',
    action: 'game.dash',
    payload: { key: 'shift' },
    options: gameGestures,
  }),
  mapping({
    id: 'interact',
    label: 'Tương tác',
    description: 'Nói chuyện, nhặt đồ hoặc mở cửa.',
    category: 'System',
    gesture_event: 'pinch_tap_interact',
    gesture: 'Pinch Tap',
    action: 'keyboard.press',
    payload: { key: 'e' },
    options: clickGestures,
  }),
  mapping({
    id: 'skill_1',
    label: 'Skill 1',
    description: 'Kỹ năng nhanh số 1.',
    category: 'Combat',
    gesture_event: 'pinch_hold_skill_1',
    gesture: 'Pinch Hold',
    action: 'game.skill_1',
    payload: { key: 'u' },
    options: poseGestures,
  }),
  mapping({
    id: 'skill_2',
    label: 'Skill 2',
    description: 'Kỹ năng nhanh số 2.',
    category: 'Combat',
    gesture_event: 'pinch_hold_skill_2',
    gesture: 'Pinch Hold Two Fingers',
    action: 'keyboard.press',
    payload: { key: 'i' },
    options: poseGestures,
  }),
  mapping({
    id: 'pause',
    label: 'Pause game',
    description: 'Mở pause menu.',
    category: 'System',
    gesture_event: 'open_close_palm_pause',
    gesture: 'Open Close Palm',
    action: 'keyboard.press',
    payload: { key: 'escape' },
    options: confirmGestures,
  }),
  mapping({
    id: 'inventory',
    label: 'Inventory',
    description: 'Mở túi đồ.',
    category: 'System',
    gesture_event: 'three_finger_pose_inventory',
    gesture: 'Three Finger Pose',
    action: 'keyboard.press',
    payload: { key: 'tab' },
    options: poseGestures,
  }),
  mapping({
    id: 'map',
    label: 'Map',
    description: 'Mở bản đồ hoặc objective.',
    category: 'System',
    gesture_event: 'four_finger_pose_map',
    gesture: 'Four Finger Pose',
    action: 'keyboard.press',
    payload: { key: 'm' },
    options: poseGestures,
  }),
]

export const localProfileDetails: Record<ConfigProfileId, ProfileDetail> = {
  office: {
    ...configProfiles[0],
    mouse: { speed: 1.5, sensitivity: 75, smoothing: 3 },
    gesture_filter: { hand: 'auto', min_confidence: 0.75, debounce_ms: 80 },
    functions: officeFunctions,
  },
  entertainment: {
    ...configProfiles[1],
    mouse: { speed: 1.2, sensitivity: 70, smoothing: 3 },
    gesture_filter: { hand: 'auto', min_confidence: 0.72, debounce_ms: 100 },
    functions: entertainmentFunctions,
  },
  game_2d: {
    ...configProfiles[2],
    mouse: { speed: 1.8, sensitivity: 82, smoothing: 2 },
    gesture_filter: { hand: 'right', min_confidence: 0.78, debounce_ms: 60 },
    functions: game2dFunctions,
  },
}

export const allGestureEvents = Array.from(
  new Set(
    Object.values(localProfileDetails).flatMap((profile) =>
      (profile.functions ?? []).flatMap((item) => [
        item.gesture_event ?? '',
        ...(item.gesture_options ?? []).map((option) => option.gesture_event),
      ]),
    ),
  ),
).filter(Boolean)

export function isConfigProfileId(profileId: string): profileId is ConfigProfileId {
  return profileId === 'office' || profileId === 'entertainment' || profileId === 'game_2d'
}

export function getLocalProfileDetail(profileId: string): ProfileDetail {
  return cloneProfile(localProfileDetails[isConfigProfileId(profileId) ? profileId : 'office'])
}

export function mergeCatalogFunctions(profileId: string, remoteFunctions: FunctionMapping[] | undefined) {
  const base = getLocalProfileDetail(profileId).functions ?? []
  const remote = remoteFunctions ?? []
  const remoteById = new Map(remote.map((item) => [item.id, item]))

  return [
    ...base.map((item) => ({ ...item, ...(remoteById.get(item.id) ?? {}) })),
    ...remote.filter((item) => !base.some((baseItem) => baseItem.id === item.id)),
  ]
}

function mapping(seed: MappingSeed): FunctionMapping {
  return {
    ...seed,
    enabled: true,
    gesture_options: seed.options,
  }
}

function cloneProfile(profile: ProfileDetail): ProfileDetail {
  return {
    ...profile,
    mouse: profile.mouse ? { ...profile.mouse } : undefined,
    gesture_filter: profile.gesture_filter ? { ...profile.gesture_filter } : undefined,
    functions: (profile.functions ?? []).map((item) => ({
      ...item,
      payload: item.payload ? { ...item.payload } : undefined,
      gesture_options: item.gesture_options?.map((option) => ({ ...option })),
    })),
  }
}
