import type { ProfileDetail } from '../api/profileApi'
import type { FunctionMapping, GestureSuggestion, Profile } from '../types'

export type ConfigProfileId = 'office' | 'entertainment' | 'game_2d' | 'custom'

type MappingSeed = Omit<FunctionMapping, 'enabled' | 'gesture_options'> & {
  options: GestureSuggestion[]
}

export const configProfiles: Profile[] = [
  {
    id: 'office',
    name: 'Văn phòng',
    description: 'Điều hướng màn hình, tài liệu, tab và kéo thả hằng ngày.',
  },
  {
    id: 'entertainment',
    name: 'Giải trí',
    description: 'Điều khiển nội dung đang phát, âm lượng, phụ đề và tốc độ.',
  },
  {
    id: 'game_2d',
    name: 'Game 2D',
    description: 'Ánh xạ hành động nhanh cho game đi cảnh 2D bằng phím quen thuộc.',
  },
  {
    id: 'custom',
    name: 'Tùy chỉnh',
    description: 'Bộ thao tác cá nhân cho quy trình riêng, macro và phím tắt đặc biệt.',
  },
]

export const actionOptions = [
  'mouse.move',
  'mouse.left_click',
  'mouse.right_click',
  'mouse.scroll',
  'mouse.down',
  'mouse.up',
  'mouse.drag',
  'keyboard.hotkey',
  'keyboard.press',
  'keyboard.release',
  'keyboard.switch_tab',
  'keyboard.copy',
  'keyboard.paste',
  'media.play_pause',
  'media.next',
  'media.previous',
  'media.volume_up',
  'media.volume_down',
  'media.seek_forward',
  'media.seek_backward',
  'media.fullscreen',
  'game.left',
  'game.right',
  'game.move_left',
  'game.move_right',
  'game.jump',
  'game.attack',
  'game.dash',
  'game.block',
  'game.crouch',
  'game.skill_1',
]

const pointerGestures: GestureSuggestion[] = [
  {
    id: 'open_palm_move',
    label: 'Lòng bàn tay mở',
    gesture_event: 'open_palm_move',
    gesture: 'Mở bàn tay để rê',
    description: 'Mở bàn tay và di chuyển cổ tay để trỏ/chọn vị trí.',
    fit: 'Tự nhiên cho điều hướng con trỏ vì MediaPipe/Hand Landmarker đọc được hướng và vị trí bàn tay.',
  },
  {
    id: 'index_point_move',
    label: 'Trỏ ngón',
    gesture_event: 'index_point_move',
    gesture: 'Trỏ ngón để rê',
    description: 'Duỗi ngón trỏ, các ngón còn lại thả lỏng để điều hướng mảnh.',
    fit: 'Phù hợp thao tác chính xác hơn khi cần rê trên vùng nhỏ.',
  },
  {
    id: 'pinch_hover_move',
    label: 'Kẹp nhẹ để rê',
    gesture_event: 'pinch_hover_move',
    gesture: 'Kẹp nhẹ để rê',
    description: 'Giữ khoảng cách ngón cái-ngón trỏ gần nhau nhưng chưa đóng click.',
    fit: 'Dễ chuyển tiếp sang click hoặc kéo thả.',
  },
]

const clickGestures: GestureSuggestion[] = [
  {
    id: 'pinch_index',
    label: 'Kẹp ngón trỏ',
    gesture_event: 'pinch_index',
    gesture: 'Kẹp ngón trỏ',
    description: 'Chạm ngón cái với ngón trỏ một nhịp ngắn.',
    fit: 'Kẹp ngón là cử chỉ chọn phổ biến, ít mỏi và dễ nhận diện qua điểm mốc đầu ngón.',
  },
  {
    id: 'air_tap',
    label: 'Chạm không trung',
    gesture_event: 'air_tap',
    gesture: 'Chạm không trung',
    description: 'Hạ nhanh ngón trỏ như bấm một nút trong không trung.',
    fit: 'Tốt cho click đơn khi người dùng quen với kiểu tap.',
  },
  {
    id: 'index_finger_pose',
    label: 'Pose một ngón',
    gesture_event: 'index_finger_pose',
    gesture: 'Giữ một ngón',
    description: 'Giữ một ngón trỏ trong 250ms để xác nhận.',
    fit: 'Dễ học, nhưng chỉ nên dùng cho shortcut có phản hồi rõ.',
  },
]

const secondaryClickGestures: GestureSuggestion[] = [
  {
    id: 'pinch_middle',
    label: 'Kẹp ngón giữa',
    gesture_event: 'pinch_middle',
    gesture: 'Kẹp ngón giữa',
    description: 'Chạm ngón cái với ngón giữa để phân biệt với click trái.',
    fit: 'Tách rõ với kẹp ngón trỏ, hợp cho click phải.',
  },
  {
    id: 'two_finger_tap',
    label: 'Tap hai ngón',
    gesture_event: 'two_finger_tap',
    gesture: 'Chạm hai ngón',
    description: 'Duỗi trỏ + giữa rồi tap nhẹ một nhịp.',
    fit: 'Gần với click phải bằng touchpad Windows.',
  },
  {
    id: 'press_hold',
    label: 'Nhấn giữ',
    gesture_event: 'press_hold',
    gesture: 'Nhấn giữ',
    description: 'Giữ bàn tay ổn định trên mục tiêu trong một khoảng ngắn.',
    fit: 'Gần với press-and-hold để mở menu ngữ cảnh trên màn hình cảm ứng.',
  },
]

const dragGestures: GestureSuggestion[] = [
  {
    id: 'pinch_drag',
    label: 'Kẹp kéo-thả',
    gesture_event: 'pinch_drag',
    gesture: 'Kẹp giữ + di chuyển + thả',
    description: 'Kẹp để giữ, di chuyển tay, mở tay để thả.',
    fit: 'Tự nhiên vì mô phỏng giữ-thả và giữ đúng quy trình kéo-thả.',
  },
  {
    id: 'closed_fist_hold',
    label: 'Nắm tay giữ',
    gesture_event: 'closed_fist_hold',
    gesture: 'Nắm tay giữ',
    description: 'Nắm tay để giữ đối tượng, mở tay để thả.',
    fit: 'Dễ hiểu như thao tác cầm vật thể.',
  },
  {
    id: 'grab_release',
    label: 'Nắm rồi thả',
    gesture_event: 'grab_release',
    gesture: 'Nắm rồi thả',
    description: 'Co các ngón để nắm, duỗi ra để thả.',
    fit: 'Phù hợp hướng dẫn theo dõi bàn tay ưu tiên thao tác nắm tự nhiên.',
  },
]

const valueGestures: GestureSuggestion[] = [
  {
    id: 'two_finger_swipe',
    label: 'Vuốt hai ngón',
    gesture_event: 'two_finger_swipe',
    gesture: 'Vuốt hai ngón',
    description: 'Vuốt hai ngón theo hướng cần cuộn/tua/chỉnh giá trị.',
    fit: 'Gần với cuộn touchpad Windows bằng hai ngón.',
  },
  {
    id: 'pinch_move_value',
    label: 'Kẹp rồi di chuyển',
    gesture_event: 'pinch_move_value',
    gesture: 'Kẹp rồi di chuyển',
    description: 'Kẹp ngón rồi kéo lên/xuống hoặc trái/phải để tăng giảm.',
    fit: 'Hợp cho thanh trượt như âm lượng, tua nội dung hoặc phóng to/thu nhỏ.',
  },
  {
    id: 'open_palm_swipe',
    label: 'Vuốt lòng bàn tay',
    gesture_event: 'open_palm_swipe',
    gesture: 'Vuốt lòng bàn tay',
    description: 'Mở bàn tay và vuốt dứt khoát theo trục thao tác.',
    fit: 'Nhanh, rõ hướng, tốt cho hành động lặp.',
  },
]

const tabGestures: GestureSuggestion[] = [
  {
    id: 'swipe_right',
    label: 'Vuốt phải',
    gesture_event: 'swipe_right',
    gesture: 'Vuốt phải',
    description: 'Vuốt ngang sang phải để tới mục tiếp theo.',
    fit: 'Tương ứng tab hoặc mục tiếp theo theo hướng thị giác.',
  },
  {
    id: 'swipe_left',
    label: 'Vuốt trái',
    gesture_event: 'swipe_left',
    gesture: 'Vuốt trái',
    description: 'Vuốt ngang sang trái để quay lại mục trước.',
    fit: 'Tương ứng tab hoặc mục trước.',
  },
  {
    id: 'three_finger_swipe',
    label: 'Vuốt ba ngón',
    gesture_event: 'three_finger_swipe',
    gesture: 'Vuốt ba ngón',
    description: 'Duỗi ba ngón rồi vuốt ngang để chuyển ngữ cảnh.',
    fit: 'Gợi nhớ cử chỉ Windows khi chuyển cửa sổ hoặc xem tác vụ.',
  },
]

const poseGestures: GestureSuggestion[] = [
  {
    id: 'two_finger_pose',
    label: 'Pose hai ngón',
    gesture_event: 'two_finger_pose',
    gesture: 'Giữ hai ngón',
    description: 'Giữ hai ngón trong 300ms để gọi shortcut.',
    fit: 'Tốt cho tác vụ ít dùng, tránh nhầm với điều hướng liên tục.',
  },
  {
    id: 'three_finger_pose',
    label: 'Pose ba ngón',
    gesture_event: 'three_finger_pose',
    gesture: 'Giữ ba ngón',
    description: 'Giữ ba ngón để gọi một chế độ hoặc lệnh hệ thống.',
    fit: 'Phù hợp hành động lớn như xem tác vụ, túi đồ hoặc bản đồ.',
  },
  {
    id: 'finger_count_shortcut',
    label: 'Shortcut số ngón',
    gesture_event: 'finger_count_shortcut',
    gesture: 'Phím tắt theo số ngón',
    description: 'Dùng số ngón làm mã shortcut nhanh.',
    fit: 'Dễ nhớ nếu UI hiển thị hướng dẫn rõ.',
  },
]

const gameGestures: GestureSuggestion[] = [
  {
    id: 'tilt',
    label: 'Nghiêng tay',
    gesture_event: 'tilt',
    gesture: 'Nghiêng tay',
    description: 'Nghiêng cổ tay sang hướng di chuyển.',
    fit: 'Tự nhiên cho trái/phải/lên/xuống và không cần pose phức tạp.',
  },
  {
    id: 'swipe_up_down',
    label: 'Vuốt lên/xuống',
    gesture_event: 'swipe_up_down',
    gesture: 'Vuốt lên/xuống',
    description: 'Vuốt dọc để nhảy, cúi hoặc đổi trục.',
    fit: 'Nhanh, rõ hướng, hợp game 2D.',
  },
  {
    id: 'rapid_punch',
    label: 'Đấm nhanh',
    gesture_event: 'rapid_punch',
    gesture: 'Đấm nhanh',
    description: 'Đẩy nắm tay ngắn về phía camera để kích hoạt hành động.',
    fit: 'Hợp với tấn công/lướt nhanh vì phản hồi nhanh và cảm giác vật lý rõ.',
  },
]

const confirmGestures: GestureSuggestion[] = [
  {
    id: 'open_close_palm',
    label: 'Mở-đóng bàn tay',
    gesture_event: 'open_close_palm',
    gesture: 'Mở/đóng bàn tay',
    description: 'Đóng rồi mở bàn tay một nhịp để bật/tắt.',
    fit: 'Hợp cho phát/tạm dừng, tắt tiếng hoặc tạm dừng game.',
  },
  {
    id: 'pinch_tap',
    label: 'Kẹp chạm nhanh',
    gesture_event: 'pinch_tap',
    gesture: 'Kẹp chạm nhanh',
    description: 'Kẹp nhanh ngón cái-ngón trỏ để xác nhận.',
    fit: 'Chọn nhanh, ít chiếm không gian thao tác.',
  },
  {
    id: 'thumbs_up',
    label: 'Giơ ngón cái',
    gesture_event: 'thumbs_up',
    gesture: 'Giơ ngón cái',
    description: 'Giơ ngón cái để xác nhận hoặc bật/tắt.',
    fit: 'Dễ hiểu nhưng nên dùng có hướng dẫn vì là tư thế cần học.',
  },
]

const officeFunctions = [
  mapping({
    id: 'move',
    label: 'Di chuyển chuột',
    description: 'Điều hướng con trỏ trên màn hình.',
    category: 'Con trỏ',
    gesture_event: 'open_palm_move',
    gesture: 'Mở bàn tay để rê',
    action: 'mouse.move',
    payload: {},
    options: pointerGestures,
  }),
  mapping({
    id: 'left_click',
    label: 'Click trái',
    description: 'Chọn file, nút hoặc ô nhập liệu.',
    category: 'Con trỏ',
    gesture_event: 'pinch_index',
    gesture: 'Kẹp ngón trỏ',
    action: 'mouse.left_click',
    payload: {},
    options: clickGestures,
  }),
  mapping({
    id: 'right_click',
    label: 'Click phải',
    description: 'Mở menu ngữ cảnh.',
    category: 'Con trỏ',
    gesture_event: 'pinch_middle',
    gesture: 'Kẹp ngón giữa',
    action: 'mouse.right_click',
    payload: {},
    options: secondaryClickGestures,
  }),
  mapping({
    id: 'double_click',
    label: 'Nhấp đúp',
    description: 'Mở file/thư mục bằng hai nhịp click.',
    category: 'Con trỏ',
    gesture_event: 'pinch_double',
    gesture: 'Kẹp đôi',
    action: 'mouse.left_click',
    payload: { clicks: 2 },
    options: clickGestures,
  }),
  mapping({
    id: 'drag_drop',
    label: 'Kéo thả file/thư mục',
    description: 'Giữ, di chuyển và thả đối tượng.',
    category: 'Con trỏ',
    gesture_event: 'pinch_drag',
    gesture: 'Kẹp giữ + di chuyển + thả',
    action: 'mouse.drag',
    payload: { state_machine: ['pinch_start', 'pinch_hold', 'drag_move', 'drag_release'] },
    options: dragGestures,
  }),
  mapping({
    id: 'scroll_up',
    label: 'Cuộn lên',
    description: 'Cuộn tài liệu hoặc trang web lên trên.',
    category: 'Điều hướng',
    gesture_event: 'two_finger_swipe_up',
    gesture: 'Vuốt hai ngón lên',
    action: 'mouse.scroll',
    payload: { amount: 5 },
    options: valueGestures,
  }),
  mapping({
    id: 'scroll_down',
    label: 'Cuộn xuống',
    description: 'Cuộn tài liệu hoặc trang web xuống dưới.',
    category: 'Điều hướng',
    gesture_event: 'two_finger_swipe_down',
    gesture: 'Vuốt hai ngón xuống',
    action: 'mouse.scroll',
    payload: { amount: -5 },
    options: valueGestures,
  }),
  mapping({
    id: 'zoom_in',
    label: 'Phóng to',
    description: 'Phóng to tài liệu/trình duyệt.',
    category: 'Điều hướng',
    gesture_event: 'pinch_spread',
    gesture: 'Kẹp rồi mở rộng',
    action: 'keyboard.hotkey',
    payload: { shortcut: 'ctrl+=' },
    options: valueGestures,
  }),
  mapping({
    id: 'zoom_out',
    label: 'Thu nhỏ',
    description: 'Giảm mức zoom tài liệu/trình duyệt.',
    category: 'Điều hướng',
    gesture_event: 'pinch_contract',
    gesture: 'Kẹp rồi thu hẹp',
    action: 'keyboard.hotkey',
    payload: { shortcut: 'ctrl+-' },
    options: valueGestures,
  }),
  mapping({
    id: 'next_tab',
    label: 'Chuyển tab phải',
    description: 'Đi tới tab kế tiếp.',
    category: 'Tab',
    gesture_event: 'three_finger_swipe_right',
    gesture: 'Vuốt ba ngón sang phải',
    action: 'keyboard.switch_tab',
    payload: { shortcut: 'ctrl+tab' },
    options: tabGestures,
  }),
  mapping({
    id: 'previous_tab',
    label: 'Chuyển tab trái',
    description: 'Quay về tab trước.',
    category: 'Tab',
    gesture_event: 'three_finger_swipe_left',
    gesture: 'Vuốt ba ngón sang trái',
    action: 'keyboard.hotkey',
    payload: { shortcut: 'ctrl+shift+tab' },
    options: tabGestures,
  }),
  mapping({
    id: 'copy',
    label: 'Sao chép',
    description: 'Sao chép vùng đang chọn.',
    category: 'Bộ nhớ tạm',
    gesture_event: 'pinch_hold_left',
    gesture: 'Kẹp giữ sang trái',
    action: 'keyboard.copy',
    payload: { shortcut: 'ctrl+c' },
    options: poseGestures,
  }),
  mapping({
    id: 'paste',
    label: 'Dán',
    description: 'Dán nội dung từ clipboard.',
    category: 'Bộ nhớ tạm',
    gesture_event: 'pinch_hold_right',
    gesture: 'Kẹp giữ sang phải',
    action: 'keyboard.paste',
    payload: { shortcut: 'ctrl+v' },
    options: poseGestures,
  }),
  mapping({
    id: 'undo',
    label: 'Hoàn tác',
    description: 'Hoàn tác thao tác gần nhất.',
    category: 'Bộ nhớ tạm',
    gesture_event: 'open_palm_twist',
    gesture: 'Xoay lòng bàn tay',
    action: 'keyboard.hotkey',
    payload: { shortcut: 'ctrl+z' },
    options: poseGestures,
  }),
  mapping({
    id: 'screenshot',
    label: 'Chụp vùng màn hình',
    description: 'Mở công cụ chọn vùng chụp màn hình.',
    category: 'Hệ thống',
    gesture_event: 'screen_pinch_capture',
    gesture: 'Kẹp chọn vùng màn hình',
    action: 'keyboard.hotkey',
    payload: { shortcut: 'win+shift+s' },
    options: poseGestures,
  }),
  mapping({
    id: 'task_view',
    label: 'Xem tác vụ',
    description: 'Xem nhanh các cửa sổ đang mở.',
    category: 'Hệ thống',
    gesture_event: 'three_finger_up',
    gesture: 'Vuốt ba ngón lên',
    action: 'keyboard.hotkey',
    payload: { shortcut: 'win+tab' },
    options: poseGestures,
  }),
]

const entertainmentFunctions = [
  mapping({
    id: 'play_pause',
    label: 'Phát / Tạm dừng',
    description: 'Bật hoặc tạm dừng nội dung đang phát.',
    category: 'Phát media',
    gesture_event: 'open_close_palm',
    gesture: 'Mở/đóng bàn tay',
    action: 'media.play_pause',
    payload: { shortcut: 'space' },
    options: confirmGestures,
  }),
  mapping({
    id: 'next_video',
    label: 'Video tiếp theo',
    description: 'Chuyển sang video/bài tiếp theo.',
    category: 'Phát media',
    gesture_event: 'swipe_right',
    gesture: 'Vuốt phải',
    action: 'media.next',
    payload: { shortcut: 'media_next' },
    options: tabGestures,
  }),
  mapping({
    id: 'previous_video',
    label: 'Video trước',
    description: 'Quay lại video/bài trước.',
    category: 'Phát media',
    gesture_event: 'swipe_left',
    gesture: 'Vuốt trái',
    action: 'media.previous',
    payload: { shortcut: 'media_previous' },
    options: tabGestures,
  }),
  mapping({
    id: 'seek_forward',
    label: 'Tua tới 10s',
    description: 'Tua nhanh nội dung về phía trước.',
    category: 'Dòng thời gian',
    gesture_event: 'two_finger_swipe_right',
    gesture: 'Vuốt hai ngón sang phải',
    action: 'media.seek_forward',
    payload: { shortcut: 'l', seconds: 10 },
    options: valueGestures,
  }),
  mapping({
    id: 'seek_backward',
    label: 'Tua lùi 10s',
    description: 'Tua lùi nội dung đang phát.',
    category: 'Dòng thời gian',
    gesture_event: 'two_finger_swipe_left',
    gesture: 'Vuốt hai ngón sang trái',
    action: 'media.seek_backward',
    payload: { shortcut: 'j', seconds: 10 },
    options: valueGestures,
  }),
  mapping({
    id: 'volume_up',
    label: 'Tăng âm lượng',
    description: 'Tăng âm lượng theo nấc.',
    category: 'Âm thanh',
    gesture_event: 'pinch_move_up_volume',
    gesture: 'Kẹp rồi di chuyển lên',
    action: 'media.volume_up',
    payload: { shortcut: 'volume_up' },
    options: valueGestures,
  }),
  mapping({
    id: 'volume_down',
    label: 'Giảm âm lượng',
    description: 'Giảm âm lượng theo nấc.',
    category: 'Âm thanh',
    gesture_event: 'pinch_move_down_volume',
    gesture: 'Kẹp rồi di chuyển xuống',
    action: 'media.volume_down',
    payload: { shortcut: 'volume_down' },
    options: valueGestures,
  }),
  mapping({
    id: 'mute',
    label: 'Tắt / bật tiếng',
    description: 'Bật hoặc tắt tiếng nhanh.',
    category: 'Âm thanh',
    gesture_event: 'thumbs_up_mute',
    gesture: 'Giơ ngón cái để bật/tắt',
    action: 'keyboard.hotkey',
    payload: { shortcut: 'm' },
    options: confirmGestures,
  }),
  mapping({
    id: 'fullscreen',
    label: 'Toàn màn hình',
    description: 'Bật hoặc thoát chế độ toàn màn hình.',
    category: 'Hiển thị',
    gesture_event: 'open_palm_hold_fullscreen',
    gesture: 'Giữ bàn tay mở',
    action: 'media.fullscreen',
    payload: { shortcut: 'f' },
    options: confirmGestures,
  }),
  mapping({
    id: 'mini_player',
    label: 'Trình phát thu nhỏ',
    description: 'Mở trình phát thu nhỏ khi xem video.',
    category: 'Hiển thị',
    gesture_event: 'two_finger_pose_mini',
    gesture: 'Giữ hai ngón',
    action: 'keyboard.hotkey',
    payload: { shortcut: 'i' },
    options: poseGestures,
  }),
  mapping({
    id: 'captions',
    label: 'Phụ đề',
    description: 'Bật hoặc tắt phụ đề.',
    category: 'Hiển thị',
    gesture_event: 'three_finger_pose_captions',
    gesture: 'Giữ ba ngón',
    action: 'keyboard.hotkey',
    payload: { shortcut: 'c' },
    options: poseGestures,
  }),
  mapping({
    id: 'speed_up',
    label: 'Tăng tốc độ phát',
    description: 'Tăng tốc độ phát lại.',
    category: 'Dòng thời gian',
    gesture_event: 'pinch_move_right_speed',
    gesture: 'Kẹp rồi di chuyển sang phải',
    action: 'keyboard.hotkey',
    payload: { shortcut: 'shift+.' },
    options: valueGestures,
  }),
  mapping({
    id: 'speed_down',
    label: 'Giảm tốc độ phát',
    description: 'Giảm tốc độ phát lại.',
    category: 'Dòng thời gian',
    gesture_event: 'pinch_move_left_speed',
    gesture: 'Kẹp rồi di chuyển sang trái',
    action: 'keyboard.hotkey',
    payload: { shortcut: 'shift+,' },
    options: valueGestures,
  }),
  mapping({
    id: 'next_frame',
    label: 'Khung hình kế tiếp',
    description: 'Khi video đang tạm dừng, tiến một khung hình.',
    category: 'Dòng thời gian',
    gesture_event: 'finger_pose_next_frame',
    gesture: 'Giữ ngón để tới khung kế tiếp',
    action: 'keyboard.hotkey',
    payload: { shortcut: '.' },
    options: poseGestures,
  }),
  mapping({
    id: 'previous_frame',
    label: 'Khung hình trước',
    description: 'Khi video đang tạm dừng, lùi một khung hình.',
    category: 'Dòng thời gian',
    gesture_event: 'finger_pose_previous_frame',
    gesture: 'Giữ ngón để lùi khung',
    action: 'keyboard.hotkey',
    payload: { shortcut: ',' },
    options: poseGestures,
  }),
]

const game2dFunctions = [
  mapping({
    id: 'move_left',
    label: 'Di chuyển trái',
    description: 'Giữ/phát phím A hoặc Left.',
    category: 'Di chuyển',
    gesture_event: 'tilt_left',
    gesture: 'Nghiêng sang trái',
    action: 'game.move_left',
    payload: { key: 'a' },
    options: gameGestures,
  }),
  mapping({
    id: 'move_right',
    label: 'Di chuyển phải',
    description: 'Giữ/phát phím D hoặc Right.',
    category: 'Di chuyển',
    gesture_event: 'tilt_right',
    gesture: 'Nghiêng sang phải',
    action: 'game.move_right',
    payload: { key: 'd' },
    options: gameGestures,
  }),
  mapping({
    id: 'move_up',
    label: 'Di chuyển lên',
    description: 'Dùng phím W cho menu hoặc game top-down.',
    category: 'Di chuyển',
    gesture_event: 'tilt_up',
    gesture: 'Nghiêng lên',
    action: 'keyboard.press',
    payload: { key: 'w' },
    options: gameGestures,
  }),
  mapping({
    id: 'move_down',
    label: 'Di chuyển xuống',
    description: 'Dùng phím S cho menu hoặc game top-down.',
    category: 'Di chuyển',
    gesture_event: 'tilt_down',
    gesture: 'Nghiêng xuống',
    action: 'keyboard.press',
    payload: { key: 's' },
    options: gameGestures,
  }),
  mapping({
    id: 'jump',
    label: 'Nhảy',
    description: 'Kích hoạt nhảy bằng Space.',
    category: 'Di chuyển',
    gesture_event: 'swipe_up',
    gesture: 'Vuốt lên',
    action: 'game.jump',
    payload: { key: 'space' },
    options: gameGestures,
  }),
  mapping({
    id: 'crouch',
    label: 'Cúi',
    description: 'Cúi hoặc rơi xuống tầng dưới.',
    category: 'Di chuyển',
    gesture_event: 'swipe_down',
    gesture: 'Vuốt xuống',
    action: 'game.crouch',
    payload: { key: 's' },
    options: gameGestures,
  }),
  mapping({
    id: 'attack',
    label: 'Tấn công',
    description: 'Đòn đánh thường.',
    category: 'Chiến đấu',
    gesture_event: 'rapid_punch',
    gesture: 'Đấm nhanh',
    action: 'game.attack',
    payload: { key: 'j' },
    tone: 'red',
    options: gameGestures,
  }),
  mapping({
    id: 'heavy_attack',
    label: 'Tấn công mạnh',
    description: 'Đòn đánh nặng hoặc đòn gồng lực.',
    category: 'Chiến đấu',
    gesture_event: 'closed_fist_punch',
    gesture: 'Đấm bằng nắm tay',
    action: 'keyboard.press',
    payload: { key: 'l' },
    tone: 'red',
    options: gameGestures,
  }),
  mapping({
    id: 'block',
    label: 'Đỡ đòn',
    description: 'Đỡ hoặc phản đòn bằng phím K.',
    category: 'Chiến đấu',
    gesture_event: 'closed_fist_hold',
    gesture: 'Nắm tay giữ',
    action: 'game.block',
    payload: { key: 'k' },
    options: dragGestures,
  }),
  mapping({
    id: 'dash',
    label: 'Lướt nhanh',
    description: 'Lướt nhanh bằng Shift.',
    category: 'Di chuyển',
    gesture_event: 'swipe_double',
    gesture: 'Vuốt đôi',
    action: 'game.dash',
    payload: { key: 'shift' },
    options: gameGestures,
  }),
  mapping({
    id: 'interact',
    label: 'Tương tác',
    description: 'Nói chuyện, nhặt đồ hoặc mở cửa.',
    category: 'Hệ thống',
    gesture_event: 'pinch_tap_interact',
    gesture: 'Kẹp chạm nhanh',
    action: 'keyboard.press',
    payload: { key: 'e' },
    options: clickGestures,
  }),
  mapping({
    id: 'skill_1',
    label: 'Kỹ năng 1',
    description: 'Kỹ năng nhanh số 1.',
    category: 'Chiến đấu',
    gesture_event: 'pinch_hold_skill_1',
    gesture: 'Kẹp giữ',
    action: 'game.skill_1',
    payload: { key: 'u' },
    options: poseGestures,
  }),
  mapping({
    id: 'skill_2',
    label: 'Kỹ năng 2',
    description: 'Kỹ năng nhanh số 2.',
    category: 'Chiến đấu',
    gesture_event: 'pinch_hold_skill_2',
    gesture: 'Kẹp giữ hai ngón',
    action: 'keyboard.press',
    payload: { key: 'i' },
    options: poseGestures,
  }),
  mapping({
    id: 'pause',
    label: 'Tạm dừng game',
    description: 'Mở menu tạm dừng.',
    category: 'Hệ thống',
    gesture_event: 'open_close_palm_pause',
    gesture: 'Mở/đóng bàn tay',
    action: 'keyboard.press',
    payload: { key: 'escape' },
    options: confirmGestures,
  }),
  mapping({
    id: 'inventory',
    label: 'Túi đồ',
    description: 'Mở túi đồ.',
    category: 'Hệ thống',
    gesture_event: 'three_finger_pose_inventory',
    gesture: 'Giữ ba ngón',
    action: 'keyboard.press',
    payload: { key: 'tab' },
    options: poseGestures,
  }),
  mapping({
    id: 'map',
    label: 'Bản đồ',
    description: 'Mở bản đồ hoặc mục tiêu nhiệm vụ.',
    category: 'Hệ thống',
    gesture_event: 'four_finger_pose_map',
    gesture: 'Giữ bốn ngón',
    action: 'keyboard.press',
    payload: { key: 'm' },
    options: poseGestures,
  }),
]

export const localProfileDetails: Record<ConfigProfileId, ProfileDetail> = {
  office: {
    ...configProfiles[0],
    mouse: { speed: 1.5, sensitivity: 75, smoothing: 3 },
    gesture_filter: { hand: 'auto', min_confidence: 0.75, debounce_ms: 80 },
    functions: officeFunctions,
  },
  entertainment: {
    ...configProfiles[1],
    mouse: { speed: 1.2, sensitivity: 70, smoothing: 3 },
    gesture_filter: { hand: 'auto', min_confidence: 0.72, debounce_ms: 100 },
    functions: entertainmentFunctions,
  },
  game_2d: {
    ...configProfiles[2],
    mouse: { speed: 1.8, sensitivity: 82, smoothing: 2 },
    gesture_filter: { hand: 'right', min_confidence: 0.78, debounce_ms: 60 },
    functions: game2dFunctions,
  },
  custom: {
    ...configProfiles[3],
    mouse: { speed: 1.5, sensitivity: 75, smoothing: 3 },
    gesture_filter: { hand: 'auto', min_confidence: 0.7, debounce_ms: 90 },
    functions: [
      mapping({
        id: 'move',
        label: 'Di chuyển chuột',
        description: 'Điều hướng con trỏ trên màn hình.',
        category: 'Con trỏ',
        gesture_event: 'open_palm_move',
        gesture: 'Mở bàn tay để rê',
        action: 'mouse.move',
        payload: {},
        options: pointerGestures,
      }),
      mapping({
        id: 'left_click',
        label: 'Click trái',
        description: 'Chọn file, nút hoặc ô nhập liệu.',
        category: 'Con trỏ',
        gesture_event: 'pinch_index',
        gesture: 'Kẹp ngón trỏ',
        action: 'mouse.left_click',
        payload: {},
        options: clickGestures,
      }),
      mapping({
        id: 'drag_drop',
        label: 'Kéo thả file/thư mục',
        description: 'Giữ, di chuyển và thả đối tượng.',
        category: 'Con trỏ',
        gesture_event: 'closed_fist_hold',
        gesture: 'Nắm tay giữ',
        action: 'mouse.drag',
        payload: { state_machine: ['pinch_start', 'pinch_hold', 'drag_move', 'drag_release'] },
        options: dragGestures,
      }),
      mapping({
        id: 'play_pause',
        label: 'Phát / Tạm dừng',
        description: 'Bật hoặc tạm dừng nội dung đang phát.',
        category: 'Phát media',
        gesture_event: 'open_close_palm',
        gesture: 'Mở/đóng bàn tay',
        action: 'media.play_pause',
        payload: {},
        options: confirmGestures,
      }),
      mapping({
        id: 'game_attack',
        label: 'Tấn công trong game',
        description: 'Đòn đánh thường cho hồ sơ tùy chỉnh.',
        category: 'Chiến đấu',
        gesture_event: 'rapid_punch',
        gesture: 'Đấm nhanh',
        action: 'game.attack',
        payload: { key: 'j' },
        tone: 'red',
        options: gameGestures,
      }),
    ],
  },
}

export const allGestureEvents = Array.from(
  new Set(
    Object.values(localProfileDetails).flatMap((profile) =>
      (profile.functions ?? []).flatMap((item) => [
        item.gesture_event ?? '',
        ...(item.gesture_options ?? []).map((option) => option.gesture_event),
      ]),
    ),
  ),
).filter(Boolean)

export function isConfigProfileId(profileId: string): profileId is ConfigProfileId {
  return profileId === 'office' || profileId === 'entertainment' || profileId === 'game_2d' || profileId === 'custom'
}

export function getLocalProfileDetail(profileId: string): ProfileDetail {
  return cloneProfile(localProfileDetails[isConfigProfileId(profileId) ? profileId : 'office'])
}

export function mergeCatalogFunctions(profileId: string, remoteFunctions: FunctionMapping[] | undefined) {
  const base = getLocalProfileDetail(profileId).functions ?? []
  const remote = remoteFunctions ?? []
  const remoteById = new Map(remote.map((item) => [item.id, item]))

  return [
    ...base.map((item) => ({ ...item, ...(remoteById.get(item.id) ?? {}) })),
    ...remote.filter((item) => !base.some((baseItem) => baseItem.id === item.id)),
  ]
}

function mapping(seed: MappingSeed): FunctionMapping {
  return {
    ...seed,
    enabled: true,
    gesture_options: seed.options,
  }
}

function cloneProfile(profile: ProfileDetail): ProfileDetail {
  return {
    ...profile,
    mouse: profile.mouse ? { ...profile.mouse } : undefined,
    gesture_filter: profile.gesture_filter ? { ...profile.gesture_filter } : undefined,
    functions: (profile.functions ?? []).map((item) => ({
      ...item,
      payload: item.payload ? { ...item.payload } : undefined,
      gesture_options: item.gesture_options?.map((option) => ({ ...option })),
    })),
  }
}
