PROCESS_SIZE = 224
MODEL_IMAGE_SIZE = 64
BOUNDING_BOX_MARGIN = 30

PREDICTION_BUFFER_SIZE = 7
STABLE_MIN_COUNT = 4

CLICK_COOLDOWN = 0.5
CLICK_FREEZE_DURATION = 0.35
FAST_CLICK_CONFIRM_FRAMES = 3
GESTURE_SWITCH_FREEZE_DURATION = 0.30
MULTI_CLICK_INTERVAL = 0.08
DRAG_PREP_FREEZE_DURATION = 0.25
DRAG_RELEASE_FREEZE_DURATION = 1.0
TAB_SWITCH_COOLDOWN = 0.75
SCROLL_COOLDOWN = 0.12

NAV_MODE = "tabs"
TAB_SWITCHES_BEFORE_APP_SWITCH = 4

MOVE_SMOOTHING = 0.50
FAST_MOVE_SMOOTHING = 0.70
HAND_POINT_SMOOTHING = 0.38
MOVE_MARGIN = 0.15
MOVE_DEAD_ZONE = 0
HAND_DEAD_ZONE = 0.0035
HAND_JUMP_GUARD = 0.085
MOVE_RESUME_FRAMES = 2
MOVE_GESTURE_CONFIRM_FRAMES = 3
HAND_REACQUIRE_FRAMES = 2
HAND_REACQUIRE_FREEZE_DURATION = 0.18
MOVE_SENSITIVITY = 2.35
MAX_MOVE_STEP = 96
HAND_EDGE_GUARD = 0.025

PINCH_ON_RATIO = 0.34
PINCH_OFF_RATIO = 0.46

CLICK_GESTURES = {"one_finger", "two_fingers"}
MOVE_GESTURES = {"open_hand", "fist", "pinch"}
NON_MOVING_GESTURES = {
    "one_finger",
    "two_fingers",
    "three_left",
    "three_right",
    "three_up",
    "three_down",
}
MODEL_ONLY_GESTURES = {"three_left", "three_right", "three_up", "three_down"}

